development:
  adapter: postgresql
  encoding: unicode
  database: geogrames_development
  pool: 5
  username: <%= `whoami` %>
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: geogrames_test
  pool: 5
  username: <%= `whoami` %>
  password:
